### ISSUE TITLE
是否支持集群？文档没看到相关的说明。

### ISSUE THREAD

**Issue by itmifen** [alibaba/jetcache#101]
集群配置是：

```
spring:
  redis:
    cluster:
      nodes:
      - redis01.ms.test:6379
      - redis02.ms.test:6379 
```

在jetcache如何配置？？求指教。
