### ISSUE TITLE
可否提供下，SpringBoot2.X 集成的demo 方式?

### ISSUE THREAD

**Issue by zhangmz0223** [alibaba/jetcache#128]
如题，集成上面好像有问题。
添加依赖后，yml 配置 也没有代码提示。

**Comment by areyouok** [comment]
配置是一样的，单元测试可以在2.x下跑通。

**Comment by zhangmz0223** [comment]
@areyouok 那我拉代码试试。

**Comment by zhangmz0223** [comment]
你好，按照这样配置出错了：

application.yml
```
jetcache:
    statIntervalMinutes: 15
    areaInCacheName: false
    hiddenPackages: com.duofriend
    #  local:
    #    default:
    #      type: linkedhashmap
    #      keyConvertor: fastjson
    remote:
        default:
            type: redis.lettuce
            keyConvertor: fastjson
            readFrom: slavePreferred
            uri:
              - redis://127.0.0.1:7032
              - redis://127.0.0.1:7033
              - redis://127.0.0.1:7035
              - redis://127.0.0.1:7030
              - redis://127.0.0.1:7031
              - redis://127.0.0.1:7034
            poolConfig:
                  minIdle: 5
                  maxIdle: 20
                  maxTotal: 50
            keyPrefix: hotel:cache
            password: 123456
            timeout: 10000
```
JavaConfig:
```java
@Slf4j
@Configuration
@AutoConfigureAfter(RedisLettuceAutoConfiguration.class)
public class JetCacheConfig {

    private final LettuceConnectionFactory lettuceConnectionFactory;

    @Autowired
    public JetCacheConfig(LettuceConnectionFactory lettuceConnectionFactory) {
        this.lettuceConnectionFactory = lettuceConnectionFactory;
    }

    @Bean(name = "defaultClient")
    @DependsOn(RedisLettuceAutoConfiguration.AUTO_INIT_BEAN_NAME)
    public LettuceFactory defaultClient() {
        return new LettuceFactory("remote.default", RedisClient.class);
    }

}

```
Application.java
```java
@EnableMethodCache(basePackages = "com.duofriend")
@EnableCreateCacheAnnotation
@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}

```


2018-07-27 09:32:10.613  WARN 63587 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisLettuceAutoInit': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com/alicp/jetcache/redis/lettuce/JetCacheCodec

@areyouok
