### ISSUE TITLE
针对Mullti Tenant(多租户)的环境，怎么配置？

### ISSUE THREAD

**Issue by dousee163** [alibaba/jetcache#146]
我原来用的是caffeine+Spring Cache方式，我在getCache的时候把TenantId当作前缀加进去解决的。
现在打算用caffeine+jetcache方式，但不知道multi tenant问题怎么解决？

**Comment by areyouok** [comment]
jetcache本身支持caffeine啊

我不知道你说的多租户是什么意思，对于redis，jetcache可以配置统一的前缀

**Comment by dousee163** [comment]
就是在一个Web应用中用不同的数据库，每个数据库对应一个完整的客户系统。如果cache不区分租户(Tenant)，就会导致租户之间的cache混淆。 统一的前缀怎么配置呢？

**Comment by areyouok** [comment]
你看看这个例子
```
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  penetrationProtect: false

  local:
    default:
      type: caffeine
      keyConvertor: fastjson
      limit: 200
      defaultExpireInMillis: 10000
    A1:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
      expireAfterAccess: true
      defaultExpireInMillis: 10000
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      poolConfig:
        minIdle: 2
        maxIdle: 5
        maxTotal: 10
      host: 127.0.0.1
      port: 6379
      defaultExpireInMillis: 10000
      keyPrefix: jedisTest
    A1:
      type: redis
      keyConvertor: fastjson
      poolConfig:
        minIdle: 2
        maxIdle: 5
        maxTotal: 10
      sentinels: 127.0.0.1:26379 , 127.0.0.1:26380, 127.0.0.1:26381
      masterName: mymaster
      valueEncoder: kryo?useIdentityNumber=false
      valueDecoder: kryo?useIdentityNumber=false
      defaultExpireInMillis: 10000
      keyPrefix: jedisTest_A1
```
