### ISSUE TITLE
请问如何为cacheName增加全局前缀？

### ISSUE THREAD

**Issue by simonuser** [alibaba/jetcache#309]
相当于增加全局的命名空间，防止不同应用公用同一个redis时cacheName发生冲突，不知道怎么实现这一点啊

**Comment by areyouok** [comment]
有这个功能，ExternalCacheAutoInit类里面，有个keyPrefix，文档里面没有写，是因为这个需求比较小众，不想让文档过于复杂。

**Comment by areyouok** [comment]
```
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      keyPrefix: xxxxxxx
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379
```
