### ISSUE TITLE
Cache 注解不起作用

### ISSUE THREAD

**Issue by YINZHU2015** [alibaba/jetcache#378]
```
@Service
public class DemoService {
    @Cached(name = "userCache:", expire = 60, cacheType = CacheType.REMOTE)
    public DemoClass getCache(@RequestParam String userId) {
        return new DemoClass("userId:[" + userId, LocalDateTime.now(), Math.random());
    }
}
```
```
@Data
public class DemoClass implements Serializable {
    private static final long serialVersionUID = 5564145052874525818L;
    private String name;
    private LocalDateTime createdDate;
    private Double age;

    public DemoClass(String name, LocalDateTime createdDate, Double age) {
        this.name = name;
        this.createdDate = createdDate;
        this.age = age;
    }
}
```

```
@RequestMapping("/demos")
@RestController
public class CacheController {

    @Autowired
    private DemoService demoService;


    @GetMapping("")
    public DemoClass getCache(@RequestParam String userId) {
        return demoService.getCache(userId);
    }
}
```
```
@SpringBootApplication
@EnableMethodCache(basePackages = "com.example.jetcachedemo")
@EnableCreateCacheAnnotation
public class JetcacheDemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(JetcacheDemoApplication.class, args);
    }

}
```

```
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      limit: 100
      keyConvertor: fastjson
      expireAfterWriteInMillis: 10000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      uri: redis://127.0.0.1:6379/
      valueEncoder: kryo
      valueDecoder: kryo
      #uri: redis-sentinel://127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381/?sentinelMasterId=mymaster
      #readFrom: slavePreferred
server:
  port: 9001
  servlet:
    context-path: /jetcache01
```

使用上面的代码和配置。执行代码跑起来以后，缓存会自动写入redis。但是每次调用contrller。都不会返回缓存内容，而是直接调用service里面的方法
