### ISSUE TITLE
获取RedisCommands报错

### ISSUE THREAD

**Issue by Skqing** [alibaba/jetcache#416]
配置：
```
jetcache:
  statIntervalMinutes: 30
  areaInCacheName: false
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      uri:
        - redis://192.168.31.2:8001
        - redis://192.168.31.2:8002
        - redis://192.168.31.2:8003
```

代码：
```
RedisCommands<byte[], byte[]> redisCommands = salesCheckCache.unwrap(RedisCommands.class);
```

错误：
```
java.lang.ClassCastException: com.sun.proxy.$Proxy109 cannot be cast to io.lettuce.core.api.sync.RedisCommands
```

如果是不是Redis集群， 只有一个Redis服务的话是正常的
