### ISSUE TITLE
redis.lettuce模式下如何配置超时时间

### ISSUE THREAD

**Issue by Skqing** [alibaba/jetcache#429]
redis.lettuce模式下如何配置超时时间
```
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      uri: redis://127.0.0.1:6379/
```
