### ISSUE TITLE
jetcache-starter-redis-lettuce 2.5.16 lettuce 管理连接时 不兼容含有“@”密码问题

### ISSUE THREAD

**Issue by ithinksky** [alibaba/jetcache#447]
1、版本
```
        <dependency>
            <groupId>com.alicp.jetcache</groupId>
            <artifactId>jetcache-starter-redis-lettuce</artifactId>
            <version>2.5.16</version>
        </dependency>
```

2、现象描述
配置如下，
```
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.alibaba
  local:
    default:
      type: caffeine
      limit: 100
      keyConvertor: fastjson
      expireAfterWriteInMillis: 100000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      uri:
        - redis://${spring.redis.password}@47.100.231.15:6379/0  #redis://密码@IP:端口/库
```
当password值包含 ‘@' 特殊符号时，
如：
```
spring.redis.password = redis@dddpwd123
```

管理连接时 不兼容含有“@”密码问题

**Comment by areyouok** [comment]
这个可能不是很好办，RedisLettuceAutoConfiguration这个类你自己改一下看看？

**Comment by lenliu2016** [comment]
最近也遇到类似问题，同时还发现密码包含字符#，也会出现问题，作者难道不打算解决该类问题吗？？

**Comment by areyouok** [comment]
是不打算支持，因为这个yml是spring boot加载的，如何转义特殊字符是spring boot的事情。

https://stackoverflow.com/questions/50672043/inside-spring-boot-application-yml-how-to-use-special-character

**Comment by whbq** [comment]
> 最近也遇到类似问题，同时还发现密码包含字符#，也会出现问题，作者难道不打算解决该类问题吗？？

也遇到这个问题了，不过明知是坑，绕过去不就是了。

**Comment by ithinksky** [comment]
> > 最近也遇到类似问题，同时还发现密码包含字符#，也会出现问题，作者难道不打算解决该类问题吗？？
> 
> 也遇到这个问题了，不过明知是坑，绕过去不就是了。

这个问题自己跟一下初始化过程的源码，稍微复写一下相关代码即可绕过去。

**Comment by hb0730** [comment]
需要转义,spring Data redis 使用`''`,而jetcache使用URL转义
比如:
```yaml
spring:
  application:
      redis:
          password: '123@!'
jetcache:
  remote:
   test:
      uri: redis://123%40%21@${spring.redis.host}:${spring.redis.port}/${spring.redis.database}
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
```
