### ISSUE TITLE
jetcache连redis创建JedisPool时，默认使用连接超时时间赋值读超时时间

### ISSUE THREAD

**Issue by ljm939066593** [alibaba/jetcache#545]
jetcache-starter-redis版本：2.5.14
yaml配置：
``` yaml
jetcache:
  statIntervalMinutes: 60
  areaInCacheName: false
  remote:
    default:
      host: ***.**.**.***
      password: ******
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      timeout: 1000
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
```
RedisAutoConfiguration中创建jedispool时 ,调用的jedispool构造函数是用timeout值默认赋值读超时时间soTimeout
```java
private Pool<Jedis> parsePool(ConfigTree ct) {
    GenericObjectPoolConfig poolConfig = parsePoolConfig(ct);

    String host = ct.getProperty("host", (String) null);
    int port = Integer.parseInt(ct.getProperty("port", "0"));
    int timeout = Integer.parseInt(ct.getProperty("timeout", String.valueOf(Protocol.DEFAULT_TIMEOUT)));
    String password = ct.getProperty("password", (String) null);
    int database = Integer.parseInt(ct.getProperty("database", String.valueOf(Protocol.DEFAULT_DATABASE)));
    String clientName = ct.getProperty("clientName", (String) null);
    boolean ssl = Boolean.parseBoolean(ct.getProperty("ssl", "false"));

    String masterName = ct.getProperty("masterName", (String) null);
    String sentinels = ct.getProperty("sentinels", (String) null);//ip1:port,ip2:port

    Pool<Jedis> jedisPool;
    if (sentinels == null) {
        Objects.requireNonNull(host, "host/port or sentinels/masterName is required");
        if (port == 0) {
            throw new IllegalStateException("host/port or sentinels/masterName is required");
        }
        jedisPool = new JedisPool(poolConfig, host, port, timeout, password, database, clientName, ssl);
    } else {
        Objects.requireNonNull(masterName, "host/port or sentinels/masterName is required");
        String[] strings = sentinels.split(",");
        HashSet<String> sentinelsSet = new HashSet<>();
        for (String s : strings) {
            if (s != null && !s.trim().equals("")) {
                sentinelsSet.add(s.trim());
            }
        }
        jedisPool = new JedisSentinelPool(masterName, sentinelsSet, poolConfig, timeout, password, database, clientName);
    }
    return jedisPool;
}
```
配置项中是否可增加读超时的配置，此处创建时可以根据配置创建jedispool
否则想控制读超时时间 比较 麻烦
