### ISSUE TITLE
是否可以自定义全局KeyConvertor?

### ISSUE THREAD

**Issue by icyfox-bupt** [alibaba/jetcache#554]
我现在需要用一个自定义的`KeyConvertor`，由于用到`@Cache`的地方很多，所以希望尽可能减少对代码的改动。
我希望的代码如下：
```
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hiddenPackages: com.sensetime.didapp
  remote:
    default:
      type: redis
      keyConvertor: myfastjson # 只改这一行
```

---

由于默认的`DefaultSpringEncoderParser`中只有一个fastjson选项。于是我想到了`DefaultSpringKeyConvertorParser`里直接获取bean的方法。
即：我自己创建一个Convertor类，标记为`@Component`，并在配置中设置为:
```
keyConvertor: bean:myFastJson
```
这个方法并不work，因为在逻辑里，会先进入`parseKeyConvertor`，再进入`setApplicationContext`。也就是说我的写法会在`getBean`时出现NPE。如下代码所示。
```
public class DefaultSpringKeyConvertorParser extends DefaultKeyConvertorParser implements ApplicationContextAware {

    private ApplicationContext applicationContext;

    @Override
    public Function<Object, Object> parseKeyConvertor(String convertor) {
        String beanName = DefaultSpringEncoderParser.parseBeanName(convertor);
        if (beanName == null) {
            return super.parseKeyConvertor(convertor);
        } else {
            return (Function<Object, Object>) applicationContext.getBean(beanName); #spring启动时先进这里
        }
    }

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.applicationContext = applicationContext;  # 后到这里
    }
}
```

所以我的问题是，除了下载代码自行修改，是否还有什么方式可以全局自定义`KeyConvertor`？ 在issues里没有看到相关讨论，谢谢各位。
