### ISSUE TITLE
RedisCacheBuild是否可以支持RedisConnectionFactory

### ISSUE THREAD

**Issue by ddilive** [alibaba/jetcache#626]
RedisCacheBuilder remoteCacheBuilder = RedisCacheBuilder.createRedisCacheBuilder()
                .keyConvertor(FastjsonKeyConvertor.INSTANCE)
                .valueEncoder(JavaValueEncoder.INSTANCE)
                .valueDecoder(JavaValueDecoder.INSTANCE)
                .jedisPool(pool);
目前只支持Pool<Jedis>构建，业务使用场景需要支持RedisConnectionFactory方式。

**Comment by ddilive** [comment]
支持RedisConnectionFactory方式，扩展性更好一些，我们业务会有多个 pool

**Comment by ddilive** [comment]
@areyouok 支持RedisConnectionFactory特性，jetcache 有计划支持吗

**Comment by areyouok** [comment]
spring-data-redis本来就支持的。

```
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  penetrationProtect: false

  local:
    default:
      type: caffeine
      keyConvertor: fastjson
      limit: 200
      defaultExpireInMillis: 10000
  remote:
    default:
      type: redis.springdata
      keyConvertor: fastjson
      defaultExpireInMillis: 10000
      keyPrefix: spring-data-redis

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000




```
