### ISSUE TITLE
升级至 Jetcache 2.6.1，Redis Key 中 会 多出一个null。

### ISSUE THREAD

**Issue by herodotus-cloud** [alibaba/jetcache#627]
### 环境：

* Jetcache 2.6.1
* Spring Boot 2.6.1（Jetcache可以正常运行，确认和 Spring Boot 版本无关）

### 个人配置

* yml 片段

```
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
      limit: 1000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
``` 

* java 代码 片段

```
 @CreateCache(name = CacheConstants.CACHE_NAME_TOKEN_SECURE_KEY, cacheType = CacheType.BOTH)
 protected Cache<String, SecretKey> cache;
```

> `CacheConstants.CACHE_NAME_TOKEN_SECURE_KEY` 的值就是：`cache:token:secure_key`.

### 问题说明

使用 Jetcache 2.6.1 版本，在Redis中存储数据的key值前面会多出一个`null`，如下所示：

```
nullcache:token:secure_key:96dac522-9c6f-47b9-*****
```

虽然并不影响实际使用，但是看着就是有点怪。也尝试Debug一下代码，水平有限没有找到具体原因。

切换回 Jetcache 2.6.0 版本，又恢复正常。重复切换版本试过几次，虽然不知道具体原因，但是确认应该就是 2.6.1 版本 问题。
