### ISSUE TITLE
阿里云的集群无法提供分片IP，只能提供一个代理域名，这时候该如何配置

### ISSUE THREAD

**Issue by Skqing** [alibaba/jetcache#646]
阿里云的集群无法提供分片IP，只能提供一个代理域名
![微信图片_20220413205051](https://user-images.githubusercontent.com/1713001/163186721-b641592f-d0d9-44a9-b3e8-e0854a9a9e25.png)

如果按照下面的配置：

```
jetcache:
  remote:
    default:
      uri: redis://xxxxxx.redis.rds.aliyuncs.com:6379/
```

就会报错：

```
[main] ERROR [org.springframework.boot.SpringApplication.reportFailure: 837] - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sportsMatchScheduled': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'lettuceHandler': Unsatisfied dependency expressed through field 'defaultClient'; nested exception is org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'defaultClient' is expected to be of type 'io.lettuce.core.cluster.RedisClusterClient' but was actually of type 'io.lettuce.core.RedisClient'
```
因为我们使用了RedisClusterClient

```
@Configuration
public class JetCacheLettuceConfig {

    @Bean(name = "defaultClient")
    @DependsOn(RedisLettuceAutoConfiguration.AUTO_INIT_BEAN_NAME)
    public LettuceFactory defaultClient() {
        return new LettuceFactory("remote.default", RedisClusterClient.class);
    }
}
```

如果把地址重复配置：

```
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      uri:
        - redis://xxxxx.redis.rds.aliyuncs.com:6379
        - redis://xxxxx.redis.rds.aliyuncs.com:6379
```

又会报下面的错误：

```
2022-04-13 18:05:32.705 [main] ERROR [org.springframework.boot.SpringApplication.reportFailure: 837] - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sportsMatchScheduled': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'lettuceHandler': Unsatisfied dependency expressed through field 'defaultClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisLettuceAutoInit' defined in class path resource [com/alicp/jetcache/autoconfigure/RedisLettuceAutoConfiguration.class]: Invocation of init method failed; nested exception is io.lettuce.core.RedisException: Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='xxxx.redis.rds.aliyuncs.com', port=6379], RedisURI [host='xxxx.redis.rds.aliyuncs.com', port=6379]]
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:321) ~[spring-context-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
```

请问如何在不改动RedisClusterClient的情况下支持阿里云的代理域名的方式？对jetcache研究不深希望能指教。

**Comment by areyouok** [comment]
以前的程序，auto configuration要填写多个uri才能识别为cluster模式。我改了一下，你自己clone一下，用2.6分支，然后
```
mvn -DskipTests clean install
```
自己build一个试试，版本号是2.6.4-SNAPSHOT。然后这样配置：

```
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      mode: cluster
      uri:
        - redis://xxxxx.redis.rds.aliyuncs.com:6379
```

如果没有问题我可以发布一个新版本。

**Comment by Skqing** [comment]
好得，多谢

**Comment by Skqing** [comment]
还是不行，看下下面这段代码是要写上readFrom这个配置才行吗？

```
protected CacheBuilder initCache(ConfigTree ct, String cacheAreaWithPrefix) {
            Map<String, Object> map = ct.subTree("uri"/*there is no dot*/).getProperties();
            String readFromStr = ct.getProperty("readFrom");
            String mode = ct.getProperty("mode");
            long asyncResultTimeoutInMillis = Long.parseLong(
                    ct.getProperty("asyncResultTimeoutInMillis", Long.toString(CacheConsts.ASYNC_RESULT_TIMEOUT.toMillis())));
            ReadFrom readFrom = null;
            if (readFromStr != null) {
                readFrom = ReadFrom.valueOf(readFromStr.trim());
            }

            AbstractRedisClient client;
            StatefulConnection connection = null;
            if (map == null || map.size() == 0) {
                throw new CacheConfigException("lettuce uri is required");
            } else {
                List<RedisURI> uriList = map.values().stream().map((k) -> RedisURI.create(URI.create(k.toString())))
                        .collect(Collectors.toList());
                if (uriList.size() == 1) {
                    RedisURI uri = uriList.get(0);
                    if (readFrom == null) {
                        client = RedisClient.create(uri);
                        ((RedisClient) client).setOptions(ClientOptions.builder().
                                disconnectedBehavior(ClientOptions.DisconnectedBehavior.REJECT_COMMANDS).build());
                    } else if ("Cluster".equalsIgnoreCase(mode)) {
                        client = RedisClusterClient.create(uri);
                        ((RedisClusterClient) client).setOptions(ClusterClientOptions.builder().
                                disconnectedBehavior(ClientOptions.DisconnectedBehavior.REJECT_COMMANDS).build());
                        if (readFrom != null) {
                            StatefulRedisClusterConnection c = ((RedisClusterClient) client).connect(new JetCacheCodec());
                            c.setReadFrom(readFrom);
                            connection = c;
                        }
                    } else {
                        client = RedisClient.create();
                        ((RedisClient) client).setOptions(ClientOptions.builder().
                                disconnectedBehavior(ClientOptions.DisconnectedBehavior.REJECT_COMMANDS).build());
                        StatefulRedisMasterReplicaConnection c = MasterReplica.connect(
                                (RedisClient) client, new JetCacheCodec(), uri);
                        c.setReadFrom(readFrom);
                        connection = c;
                    }
```

**Comment by Skqing** [comment]
> 以前的程序，auto configuration要填写多个uri才能识别为cluster模式。我改了一下，你自己clone一下，用2.6分支，然后
> 
> ```
> mvn -DskipTests clean install
> ```
> 
> 自己build一个试试，版本号是2.6.4-SNAPSHOT。然后这样配置：
> 
> ```
>   remote:
>     default:
>       type: redis.lettuce
>       keyConvertor: fastjson
>       valueEncoder: java
>       valueDecoder: java
>       mode: cluster
>       uri:
>         - redis://xxxxx.redis.rds.aliyuncs.com:6379
> ```
> 
> 如果没有问题我可以发布一个新版本。

**Comment by areyouok** [comment]
和read from没有关系，现在我也不太清楚这个原因是什么。

**Comment by areyouok** [comment]
阿里云似乎不推荐使用lettuce？你直接裸用lettuce client能写出连上去的代码吗

**Comment by Skqing** [comment]
> 阿里云似乎不推荐使用lettuce？你直接裸用lettuce client能写出连上去的代码吗

我试一下看看

**Comment by Skqing** [comment]
> readFrom

如果readFrom是空，mode: cluster这个配置不就没意义了吗，集群情况下

**Comment by areyouok** [comment]
那里是有点问题，我补了一个提交，不过和你遇到的问题无关

**Comment by Skqing** [comment]
问题已解决，使用阿里云的配置：

```
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      mode: cluster
      uri:
        - redis://pwd@xxxxx.redis.rds.aliyuncs.com:6379
```

注意地址要加密码，并且是default账号的密码
