### ISSUE TITLE
关于CacheType.LOCAL+CacheRefresh 内存泄漏?

### ISSUE THREAD

**Issue by zt9788** [alibaba/jetcache#778]
感觉我这个问题和#640 比较像
YML:

```
jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      limit: 100
```

Code:

```
@Cached(name="test", key="'list'",cacheType = CacheType.LOCAL)
@CacheRefresh(refresh = 60, timeUnit = TimeUnit.MINUTES, stopRefreshAfterLastAccess = 120)
public list<TestObj> list(){
   return list(1000);//
}   
```
从jmap来看TestObj会越来越多,并且不会释放?
所以是配置问题? 删除CacheRefresh?还是其他问题导致呢 ?
