### ISSUE TITLE
LinkedHashMapCache设计问题讨论

### ISSUE THREAD

**Issue by wangguanquan** [alibaba/jetcache#943]
LinkedHashMapCache使用LinkedHashMap实现，实例化时会固定传入`accessOrder=true`，当accessOrder为true时访问数据后会将当前节点移到队列尾部，当过期策略设置为isExpireAfterAccess时没有问题，最近访问的数据会放到队尾那么队列头部均是最早被淘汰的，但是当过期策略是isExpireAfterWrite时就会因这些移尾的行为打乱进入队列的位置，队列头部的数据并不能保证优先被淘汰，只有保留入队顺序才能更快的找到淘汰数据，所以需要根据config里的过期策略来设计accessOrder的值。

优化建议：
1. LRUMap实例化时根据过期策略判断accessOrder值
2. 过期扫描不需要扫描全表只需要扫描队列头即可，当出现第一个不满足淘汰的节点即中断
3. 可以设置单次淘汰数量以缓解因数量过多持有锁时间长影响正常访问

另外建议LinkedHashMapAutoConfiguration添加map关键词，linkedhashmap名称太长且不需要向外暴露实现方法，改为map更简洁且不容易拼写错误
```
jetcache:
  local:
    default:
      type: map
      keyConvertor: fastjson
```
